project_id = "ofwhxaglbcgyksauwjby"

[functions.generate-recommendations]
verify_jwt = false

[functions.upsert-ventas-cupra]
verify_jwt = false

[functions.upsert-clientes]
verify_jwt = false

[functions.upsert-client-places]
verify_jwt = false

[functions.upsert-prospectos]
verify_jwt = false

[functions.cleanup-visited-assignments]
verify_jwt = false

[functions.check-pending-assignments]
verify_jwt = false

[functions.process-ventas-excel]
verify_jwt = false

[functions.geocode-clients]
verify_jwt = false

[functions.prospect-discovery]
verify_jwt = false

[functions.extract-feedback]
verify_jwt = false
