CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE TABLE public.profiles(user_id uuid PRIMARY KEY,rol text,activo boolean DEFAULT true);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION public.is_assignor_like(uid uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE user_id=uid AND rol IN ('administrador','asignador')) $$;
CREATE TABLE public.clientes (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "cuit_dni" text,
  "razon_social" text,
  "last_recommendation_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "client_id" text NOT NULL,
  "todos_barrios" text[] DEFAULT '{}'::text[],
  "todas_direcciones" text[] DEFAULT '{}'::text[],
  "todos_vendedores" text[] DEFAULT '{}'::text[],
  "requiere_visita" text,
  "canal" text,
  "etiquetas" text[] DEFAULT '{}'::text[],
  "fantasia" text,
  "primera_compra" date,
  "ultima_compra" date,
  "dias_desde_ultima_compra" integer,
  "cantidad_ordenes" integer DEFAULT 0,
  "monto_total_historico" numeric DEFAULT 0,
  "ticket_promedio" numeric DEFAULT 0,
  "categoria_recencia" text,
  "categoria_volumen" text,
  "score_recencia" integer,
  "score_volumen" integer,
  "score_comercial" integer,
  "participacion_mercado" numeric,
  "ciudad_principal" text,
  "barrio_principal" text,
  "direccion_principal" text,
  "provincia_principal" text,
  "vendedor_principal" text,
  "productos_comprados" text[] DEFAULT '{}'::text[],
  "todas_ciudades" text[] DEFAULT '{}'::text[],
  "ultima_visita" timestamp with time zone,
  "excluir_recomendaciones" boolean DEFAULT false,
  "telefonos" text[] DEFAULT '{}'::text[],
  "emails" text[] DEFAULT '{}'::text[],
  "motivo_exclusion" text,
  "vendedor_actual" text,
  "monto_notas_credito" numeric DEFAULT 0,
  "fecha_ultima_nc" date,
  "cadencia_dias" integer,
  "precio_promedio_caja" numeric,
  "monto_total_cupra" numeric,
  "share_cupra" numeric,
  "fuente_monto" text DEFAULT 'producto'::text NOT NULL,
  "monto_nc_producto" numeric DEFAULT 0 NOT NULL,
  "monto_nc_concepto" numeric DEFAULT 0 NOT NULL,
  "codigo_postal" text,
  "rubro" text,
 PRIMARY KEY(id), UNIQUE(client_id)
);
CREATE TABLE public.client_places (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_id" text NOT NULL,
  "barrio_principal" text,
  "direccion_principal" text,
  "provincia_principal" text,
  "comuna" text,
  "lat" numeric NOT NULL,
  "long" numeric NOT NULL,
  "place_id" text,
  "google_maps_link" text,
  "is_primary" boolean DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "direccion_verificada" boolean DEFAULT false NOT NULL,
  "fuente_geocoding" text DEFAULT 'geocoding_auto'::text,
  "codigo_postal" text,
  "precision_geocoding" text,
  "ubicacion_confiable" boolean DEFAULT false NOT NULL,
 PRIMARY KEY(id), UNIQUE(client_id,lat,long), UNIQUE(client_id,direccion_principal)
);
CREATE TABLE public.prospectos (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "place_id" text NOT NULL,
  "client_id" text,
  "nombre" text NOT NULL,
  "telefono" text,
  "direccion" text NOT NULL,
  "barrio" text,
  "comuna" text,
  "ciudad" text NOT NULL,
  "provincia" text NOT NULL,
  "latitud" numeric NOT NULL,
  "longitud" numeric NOT NULL,
  "rating" numeric DEFAULT 0,
  "total_ratings" integer DEFAULT 0,
  "nivel_precio" text,
  "tipo_principal" text,
  "tipos" text[] DEFAULT '{}'::text[],
  "sirve_vinos" boolean DEFAULT false,
  "website" text,
  "estado_negocio" text,
  "es_cliente_cupra" boolean DEFAULT false,
  "last_recommendation_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "email" text,
  "instagram" text,
  "resumen_google" text,
  "rubro" text,
 PRIMARY KEY(id), UNIQUE(place_id)
);
CREATE SEQUENCE ventas_cupra_id_seq;
CREATE TABLE public.ventas_cupra (
  "id" bigint DEFAULT nextval('ventas_cupra_id_seq'::regclass) NOT NULL,
  "client_id" text,
  "ticket" text,
  "letra" text,
  "fecha_emision" date,
  "cuit_dni" text,
  "razon_social" text,
  "fantasia" text,
  "cajas" integer,
  "codigo_producto" text,
  "nombre" text,
  "marca" text,
  "facturacion_ars" numeric,
  "vendedor" text,
  "telefono" text,
  "celular" text,
  "correo" text,
  "direccion" text,
  "ciudad" text,
  "provincia" text,
  "pais" text,
  "categorias" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "tipo_comprobante" text DEFAULT 'venta'::text NOT NULL,
  "import_batch_id" uuid,
  "bonificacion" numeric,
  "renglon" integer DEFAULT 1 NOT NULL,
 PRIMARY KEY(id)
);
CREATE SEQUENCE ventas_cupra_eliminadas_id_seq;
CREATE TABLE public.ventas_cupra_eliminadas (
  "id" bigint DEFAULT nextval('ventas_cupra_eliminadas_id_seq'::regclass) NOT NULL,
  "batch_id" uuid,
  "motivo" text DEFAULT 'eliminada'::text NOT NULL,
  "venta_id" bigint,
  "client_id" text,
  "ticket" text,
  "letra" text,
  "fecha_emision" date,
  "cuit_dni" text,
  "razon_social" text,
  "fantasia" text,
  "cajas" integer,
  "codigo_producto" text,
  "nombre" text,
  "marca" text,
  "facturacion_ars" numeric,
  "vendedor" text,
  "telefono" text,
  "celular" text,
  "correo" text,
  "direccion" text,
  "ciudad" text,
  "provincia" text,
  "pais" text,
  "categorias" text,
  "tipo_comprobante" text,
  "import_batch_id" uuid,
  "eliminada_at" timestamp with time zone DEFAULT now() NOT NULL,
  "bonificacion" numeric,
  "renglon" integer,
 PRIMARY KEY(id)
);
CREATE TABLE public.import_batches (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tipo" text NOT NULL,
  "estado" text DEFAULT 'procesando'::text NOT NULL,
  "version_etl" text NOT NULL,
  "archivo_nombre" text NOT NULL,
  "archivo_sha256" text,
  "archivo_tamano" bigint,
  "archivo_ultima_modificacion" timestamp with time zone,
  "hoja" text,
  "fila_encabezado" integer,
  "filas_origen" integer DEFAULT 0 NOT NULL,
  "filas_notas_credito" integer DEFAULT 0 NOT NULL,
  "reemplaza_existentes" boolean DEFAULT false NOT NULL,
  "usuario_id" uuid,
  "usuario_email" text,
  "resultado" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "calidad" jsonb,
  "reconciliacion" jsonb,
  "error_message" text,
  "started_at" timestamp with time zone DEFAULT now() NOT NULL,
  "completed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "fecha_desde" date,
  "fecha_hasta" date,
  "modo_carga" text DEFAULT 'rango'::text NOT NULL,
  "clientes_archivo" integer,
  "total_bruto" numeric,
  "filas_insertadas" integer,
  "filas_actualizadas" integer,
  "filas_eliminadas" integer,
  "revertido_at" timestamp with time zone,
 PRIMARY KEY(id), CONSTRAINT import_batches_tipo_check CHECK (tipo IN ('ventas','maestro')), CONSTRAINT import_batches_estado_check CHECK (estado IN ('procesando','completado','completado_con_errores','fallido'))
);
CREATE TABLE public.import_staging_rows (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" uuid NOT NULL,
  "tipo_fila" text NOT NULL,
  "numero_fila" integer NOT NULL,
  "payload" jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "expires_at" timestamp with time zone DEFAULT (now() + '7 days'::interval) NOT NULL,
 PRIMARY KEY(id), UNIQUE(batch_id,tipo_fila,numero_fila)
);
