-- Trazabilidad y recuperacion de las cargas de maestro/ventas.
-- Las Edge Functions escriben con service_role; los asignadores solo pueden consultar.

CREATE TABLE IF NOT EXISTS public.import_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo text NOT NULL CHECK (tipo IN ('maestro', 'ventas')),
  estado text NOT NULL DEFAULT 'procesando'
    CHECK (estado IN ('procesando', 'completado', 'completado_con_errores', 'fallido')),
  version_etl text NOT NULL,
  archivo_nombre text NOT NULL,
  archivo_sha256 text,
  archivo_tamano bigint CHECK (archivo_tamano IS NULL OR archivo_tamano >= 0),
  archivo_ultima_modificacion timestamptz,
  hoja text,
  fila_encabezado integer CHECK (fila_encabezado IS NULL OR fila_encabezado > 0),
  filas_origen integer NOT NULL DEFAULT 0 CHECK (filas_origen >= 0),
  filas_notas_credito integer NOT NULL DEFAULT 0 CHECK (filas_notas_credito >= 0),
  reemplaza_existentes boolean NOT NULL DEFAULT false,
  usuario_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  usuario_email text,
  resultado jsonb NOT NULL DEFAULT '{}'::jsonb,
  calidad jsonb,
  reconciliacion jsonb,
  error_message text,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_import_batches_created_at
  ON public.import_batches (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_batches_tipo_estado
  ON public.import_batches (tipo, estado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_batches_sha256
  ON public.import_batches (archivo_sha256)
  WHERE archivo_sha256 IS NOT NULL;

GRANT SELECT ON public.import_batches TO authenticated;
GRANT ALL ON public.import_batches TO service_role;

ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Asignadores pueden ver historial de importaciones" ON public.import_batches;
CREATE POLICY "Asignadores pueden ver historial de importaciones"
  ON public.import_batches
  FOR SELECT
  TO authenticated
  USING (public.get_user_role(auth.uid()) = 'asignador'::public.app_role);

CREATE TABLE IF NOT EXISTS public.import_staging_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.import_batches(id) ON DELETE CASCADE,
  tipo_fila text NOT NULL CHECK (tipo_fila IN ('principal', 'nota_credito')),
  numero_fila integer NOT NULL CHECK (numero_fila > 0),
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  UNIQUE (batch_id, tipo_fila, numero_fila)
);

CREATE INDEX IF NOT EXISTS idx_import_staging_rows_batch
  ON public.import_staging_rows (batch_id, tipo_fila, numero_fila);
CREATE INDEX IF NOT EXISTS idx_import_staging_rows_expires_at
  ON public.import_staging_rows (expires_at);

GRANT SELECT ON public.import_staging_rows TO authenticated;
GRANT ALL ON public.import_staging_rows TO service_role;

ALTER TABLE public.import_staging_rows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Asignadores pueden ver staging de importaciones" ON public.import_staging_rows;
CREATE POLICY "Asignadores pueden ver staging de importaciones"
  ON public.import_staging_rows
  FOR SELECT
  TO authenticated
  USING (
    public.get_user_role(auth.uid()) = 'asignador'::public.app_role
    AND EXISTS (
      SELECT 1
      FROM public.import_batches b
      WHERE b.id = import_staging_rows.batch_id
    )
  );

CREATE OR REPLACE FUNCTION public.cleanup_expired_import_staging()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM public.import_staging_rows WHERE expires_at < now();
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_expired_import_staging() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cleanup_expired_import_staging() FROM anon;
REVOKE ALL ON FUNCTION public.cleanup_expired_import_staging() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_import_staging() TO service_role;

CREATE OR REPLACE FUNCTION public.commit_ventas_import(
  p_rows jsonb,
  p_replace_existing boolean DEFAULT true
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  affected_count integer;
BEGIN
  IF jsonb_typeof(p_rows) <> 'array' OR jsonb_array_length(p_rows) = 0 THEN
    RAISE EXCEPTION 'El lote de ventas no contiene filas';
  END IF;

  IF p_replace_existing THEN
    DELETE FROM public.ventas_cupra;
  ELSE
    DELETE FROM public.ventas_cupra current_sale
    USING jsonb_to_recordset(p_rows) AS incoming(
      ticket text, letra text, fecha_emision date, client_id text,
      codigo_producto text, facturacion_ars numeric
    )
    WHERE current_sale.ticket IS NOT DISTINCT FROM incoming.ticket
      AND COALESCE(current_sale.letra, '') = COALESCE(incoming.letra, '')
      AND COALESCE(current_sale.fecha_emision, DATE '1900-01-01') = COALESCE(incoming.fecha_emision, DATE '1900-01-01')
      AND COALESCE(current_sale.client_id, '') = COALESCE(incoming.client_id, '')
      AND COALESCE(current_sale.codigo_producto, '') = COALESCE(incoming.codigo_producto, '')
      AND COALESCE(current_sale.facturacion_ars, 0) = COALESCE(incoming.facturacion_ars, 0);
  END IF;

  INSERT INTO public.ventas_cupra (
    ticket, letra, fecha_emision, cuit_dni, razon_social, fantasia,
    cajas, codigo_producto, nombre, marca, facturacion_ars, vendedor,
    telefono, celular, correo, direccion, ciudad, provincia, pais,
    categorias, client_id
  )
  SELECT
    incoming.ticket, incoming.letra, incoming.fecha_emision,
    incoming.cuit_dni, incoming.razon_social, incoming.fantasia,
    incoming.cajas, incoming.codigo_producto, incoming.nombre,
    incoming.marca, incoming.facturacion_ars, incoming.vendedor,
    incoming.telefono, incoming.celular, incoming.correo,
    incoming.direccion, incoming.ciudad, incoming.provincia,
    incoming.pais, incoming.categorias, incoming.client_id
  FROM jsonb_to_recordset(p_rows) AS incoming(
    ticket text,
    letra text,
    fecha_emision date,
    cuit_dni text,
    razon_social text,
    fantasia text,
    cajas integer,
    codigo_producto text,
    nombre text,
    marca text,
    facturacion_ars numeric,
    vendedor text,
    telefono text,
    celular text,
    correo text,
    direccion text,
    ciudad text,
    provincia text,
    pais text,
    categorias text,
    client_id text
  );

  GET DIAGNOSTICS affected_count = ROW_COUNT;
  RETURN affected_count;
END;
$$;

REVOKE ALL ON FUNCTION public.commit_ventas_import(jsonb, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.commit_ventas_import(jsonb, boolean) FROM anon;
REVOKE ALL ON FUNCTION public.commit_ventas_import(jsonb, boolean) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.commit_ventas_import(jsonb, boolean) TO service_role;
